[tool.poetry]
name = "da-index"
version = "0.1.0"
description = "Deterioration Allocation Index Framework"
authors = ["Honghan <honghan.wu@gmail.com>", "HarrisonWilde <h.wilde@ucl.ac.uk>"]
license = "LICENSE"
readme = "README.md"
repository = "https://github.com/knowlab/DAindex-Framework"
keywords = ["evaluation", "fairness", "machine learning", "data science", "bias"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License", # TODO: is it MIT? The License file implies maybe not?
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.2.2"
numpy = "^2.1.1"
matplotlib = "^3.9.2"
scikit-learn = "^1.5.1"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
jupyter = "^1.1.1"
notebook = "^7.2.2"
tox = "^4.18.0"
ruff = "^0.6.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
