name: "Tox"

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.10", "3.11", "3.12"]

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4
      - name: Setup python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Load cached Poetry installation
        id: cached-poetry
        uses: actions/cache@v4
        with:
          path: ~/.local
          key: poetry-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}
      - name: Install Poetry
        if: steps.cached-poetry.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1
      - name: Configure Poetry
        run: poetry config virtualenvs.in-project true
      - name: Install tox
        run: pip install tox
      - name: Run tox
        run: tox -e py
